// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AutoDiff from "../AutoDiff.res.mjs";
import * as Optimizer from "../Optimizer.res.mjs";

var MyTerm = AutoDiff.MakeTerm({});

var MyExtraOps = AutoDiff.ExtraOperators(MyTerm);

function linearModel(nInputs, iterationOpt) {
  var iteration = iterationOpt !== undefined ? iterationOpt : 100;
  var init = function () {
    return Math.random() * 2.0 - 0.5;
  };
  var optimizer = Optimizer.adam(undefined, undefined, undefined, undefined, nInputs + 1 | 0);
  var weights = MyTerm.claimMany(nInputs, init);
  var bias = MyTerm.claim(init);
  var model = function (xs) {
    return MyTerm.$plus(MyExtraOps.dotproduct(weights, xs), bias);
  };
  var loss = function (guessed, actual) {
    var actual$1 = actual.map(MyTerm.c);
    return MyExtraOps.mean(MyExtraOps.$neg$dot(guessed, actual$1).map(function (d) {
                    return MyTerm.pow(d, 2.0);
                  }));
  };
  var $$eval = MyTerm.$$eval;
  var init$1 = MyTerm.initEnv;
  return function (dataset) {
    return Optimizer.learn($$eval, model, loss, dataset, optimizer, iteration, init$1);
  };
}

export {
  MyTerm ,
  MyExtraOps ,
  linearModel ,
}
/* MyTerm Not a pure module */
