// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utilities from "./Utilities.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function MakeTerm(Nat) {
  var nVariable = Nat.n;
  var makeEnv = function (m) {
    return Utilities.buildArray(nVariable, (function (param) {
                  return m();
                }));
  };
  var claimed = {
    contents: 0
  };
  var claim = function () {
    var i = claimed.contents;
    if (i < nVariable) {
      claimed.contents = claimed.contents + 1 | 0;
      return {
              TAG: "Var",
              _0: i
            };
    } else {
      return PervasivesU.failwith("Not enough variables");
    }
  };
  var claimMany = function (n) {
    if (n === 0) {
      return [];
    } else {
      return Belt_Array.concatMany([
                  [claim()],
                  claimMany(n - 1 | 0)
                ]);
    }
  };
  var $$eval = function (term, env) {
    if (term.TAG !== "Var") {
      return term._0(env);
    }
    var i = term._0;
    var d = Core__Array.make(nVariable, 0.0);
    return {
            output: Core__Option.getExn(env[i], undefined),
            derivative: (d[i] = 1.0, d)
          };
  };
  var checkEq = function (test, m1, m2) {
    var checkCloseEnough = function (x, y, s) {
      if (!Utilities.closeEnough(x, y)) {
        console.log("fail check:", s);
        console.log("- received:", x);
        console.log("- expected:", y);
        return ;
      }
      
    };
    checkCloseEnough(m1.output, m2.output, test + "-output");
    Utilities.map2(m1.derivative, m2.derivative, (function (d1, d2) {
            checkCloseEnough(d1, d2, test + "-derivative");
          }));
  };
  var spy = function (x, name) {
    return {
            TAG: "Term",
            _0: (function (env) {
                var x$1 = $$eval(x, env);
                console.log(name + " =", x$1.output);
                return x$1;
              })
          };
  };
  var c = function (v) {
    return {
            TAG: "Term",
            _0: (function (_env) {
                return {
                        output: v,
                        derivative: Core__Array.make(nVariable, 0.0)
                      };
              })
          };
  };
  var $plus = function (x, y) {
    return {
            TAG: "Term",
            _0: (function (env) {
                var x$1 = $$eval(x, env);
                var y$1 = $$eval(y, env);
                return {
                        output: x$1.output + y$1.output,
                        derivative: Utilities.vadd(x$1.derivative, y$1.derivative)
                      };
              })
          };
  };
  var $star = function (x, y) {
    return {
            TAG: "Term",
            _0: (function (env) {
                var x$1 = $$eval(x, env);
                var y$1 = $$eval(y, env);
                return {
                        output: x$1.output * y$1.output,
                        derivative: Utilities.vadd(Utilities.emul(x$1.derivative, y$1.output), Utilities.emul(y$1.derivative, x$1.output))
                      };
              })
          };
  };
  var pow = function (x, n) {
    return {
            TAG: "Term",
            _0: (function (env) {
                var x$1 = $$eval(x, env);
                return {
                        output: Utilities.BoundMath.pow(x$1.output, n),
                        derivative: Utilities.emul(x$1.derivative, n * Utilities.BoundMath.pow(x$1.output, n - 1.0))
                      };
              })
          };
  };
  var exp = function (x) {
    return {
            TAG: "Term",
            _0: (function (env) {
                var x$1 = $$eval(x, env);
                return {
                        output: Utilities.BoundMath.exp(x$1.output),
                        derivative: Utilities.emul(x$1.derivative, Utilities.BoundMath.exp(x$1.output))
                      };
              })
          };
  };
  var log = function (x) {
    return {
            TAG: "Term",
            _0: (function (env) {
                var x$1 = $$eval(x, env);
                return {
                        output: Utilities.BoundMath.log(x$1.output),
                        derivative: Utilities.emul(x$1.derivative, 1.0 / x$1.output)
                      };
              })
          };
  };
  var $eq = function (x, y) {
    return function (env) {
      var x$1 = $$eval(x, env);
      var y$1 = $$eval(y, env);
      return x$1.output === y$1.output;
    };
  };
  var $less = function (x, y) {
    return function (env) {
      var x$1 = $$eval(x, env);
      var y$1 = $$eval(y, env);
      return x$1.output < y$1.output;
    };
  };
  var ifte = function (b, x, y) {
    return {
            TAG: "Term",
            _0: (function (env) {
                if (b(env)) {
                  return $$eval(x, env);
                } else {
                  return $$eval(y, env);
                }
              })
          };
  };
  var $pipe$pipe = function (a, b) {
    return function (env) {
      if (a(env)) {
        return true;
      } else {
        return b(env);
      }
    };
  };
  var $amp$amp = function (a, b) {
    return function (env) {
      if (a(env)) {
        return b(env);
      } else {
        return false;
      }
    };
  };
  var not = function (a) {
    return function (env) {
      return !a(env);
    };
  };
  return {
          makeEnv: makeEnv,
          spy: spy,
          $$eval: $$eval,
          claim: claim,
          claimMany: claimMany,
          c: c,
          $plus: $plus,
          $star: $star,
          $less: $less,
          $eq: $eq,
          not: not,
          $amp$amp: $amp$amp,
          $pipe$pipe: $pipe$pipe,
          pow: pow,
          exp: exp,
          log: log,
          ifte: ifte,
          checkEq: checkEq
        };
}

function ExtraOperators(Term) {
  var $tilde$neg = function (x) {
    return Term.$star(Term.c(-1.0), x);
  };
  var $neg = function (x, y) {
    return Term.$plus(x, $tilde$neg(y));
  };
  var $slash = function (x, y) {
    return Term.$star(x, Term.pow(y, -1.0));
  };
  var $great = function (x, y) {
    return Term.$less(y, x);
  };
  var $less$eq = function (x, y) {
    return Term.$pipe$pipe(Term.$less(x, y), Term.$eq(x, y));
  };
  var $great$eq = function (x, y) {
    return Term.$pipe$pipe(Term.$less(y, x), Term.$eq(x, y));
  };
  var $bang$eq = function (x, y) {
    return Term.not(Term.$eq(x, y));
  };
  var sigmoid = function (x) {
    return $slash(Term.c(1.0), Term.$plus(Term.c(1.0), Term.exp($tilde$neg(x))));
  };
  var max = function (x, y) {
    return Term.ifte($great$eq(x, y), x, y);
  };
  var min = function (x, y) {
    return Term.ifte($less$eq(x, y), x, y);
  };
  var reLU = function (x) {
    return max(x, Term.c(0.0));
  };
  var leakyReLU = function (x) {
    var y = Term.c(0.0);
    return Term.ifte(Term.$less(y, x), x, Term.$star(Term.c(0.1), x));
  };
  var reELU = function (x) {
    return Term.ifte(Term.$less(x, Term.c(0.0)), Term.exp(x), x);
  };
  var dotproduct = function (v1, v2) {
    return Core__Array.reduce(Utilities.map2(v1, v2, Term.$star), Term.c(0.0), Term.$plus);
  };
  return {
          $tilde$neg: $tilde$neg,
          $neg: $neg,
          $slash: $slash,
          $great: $great,
          $less$eq: $less$eq,
          $great$eq: $great$eq,
          $bang$eq: $bang$eq,
          sigmoid: sigmoid,
          max: max,
          min: min,
          reLU: reLU,
          leakyReLU: leakyReLU,
          reELU: reELU,
          dotproduct: dotproduct
        };
}

export {
  MakeTerm ,
  ExtraOperators ,
}
/* No side effect */
